### ISSUE TITLE
greet

### ISSUE THREAD

**Issue by longczx** [phuongnam8290/glitch-novels#1]
Hello, are you going to continue to maintain this project? I looked at the page. It's perfect, but at present, there are only display pages, not novel reading pages.

**Comment by phuongnam8290** [comment]
Hi!
Firstly, please excuse my poor English.
Yes, I planned to continue to work on this project, but since it's a pet project and I'm busy right now, the update interval will be erratic.
Also, I'm still learning and planning to change the UI quite a bit, so the result may not suit your need.

**Comment by longczx** [comment]
Well, isn't your native language English? Take the liberty of asking where you come from. In addition, I am looking for a Vue project that can be used to read novels on mobile phones. Thank you for letting me see the direction of your project

**Comment by phuongnam8290** [comment]
I'm from Vietnam.
Running smoothly on mobile devices is also one of my main concerns. But at the moment, it's still quite janky, and need more time to sort out the problems.
If you need anything else, please email me =))
